- hosts: localhost
  become: yes
  tasks:
    - name: Install general packages which I need in the server
      apt:
        name:
          - tree
          - vim
          - python3
          - python3-pip
          - python3-apt
        state: present
        update_cache: true
      tags:
        - general-packages
        - tree

    - name: install docker pip package
      pip:
        name:
          - docker
        state: present
    - name: Build an image and push it to a private repo
      community.docker.docker_image:
         build:
            path: "/home/edureka/Desktop"
         name: docker.io/jyotshna7/abctechnologies
         #tag: test
         push: true
         source: build
      register: out
    - debug:
         var: out  
    - name: start a container
      community.docker.docker_container:
         name: abc-application
         image: jyotshna7/abctechnologies
         state: started
         ports:
            - 1234:8080
         #restart: true
      register: out
    - debug:
         var: out
         #- name: Deploying to kubernetes
    - name: Create a Deployment by reading the definition from a local file 
      command: "kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f /home/edureka/Desktop/deployment.yml"    
      register: out
    - debug:
         var: out
